version: '3.8'

services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: pruebadbcon
    image: pruebadbimage
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pruebanet

  app:
    build:
      context: ./BACK
      dockerfile: Dockerfile
    container_name: pruebabackcon
    image: pruebabackimage
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: ["sh", "-c", "sleep 10 && npm run start:prod"]
    networks:
      - pruebanet  

  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    container_name: pruebauicon
    image: pruebauiimage
    environment:
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - pruebanet

volumes:
  postgres_data:
    name: datapruebadb

networks:
  pruebanet:
    name: pruebanet