version: '3.8'

services:
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: pruebadbcon
    image: pruebadbimage
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prueba123
      POSTGRES_DB: felipedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pruebanet

  app:
    build:
      context: ./BACK
      dockerfile: Dockerfile
    container_name: pruebabackcon
    image: pruebabackimage
    environment:
      DATABASE_URL: "postgresql://postgres:prueba123@db:5432/felipedb?schema=public"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: ["sh", "-c", "sleep 10 && npm run start:prod"]
    networks:
      - pruebanet

volumes:
  postgres_data:
    name: datapruebadb

networks:
  pruebanet:
    name: pruebanet